name: Measure Definitions
modelClass: Pensoft\RestcoastMobileApp\Models\MeasureDefinition
form: $/pensoft/restcoastmobileapp/models/measure-definition/fields.yaml
defaultRedirect: pensoft/restcoastmobileapp/measuredefinitions
create:
    redirect: 'pensoft/restcoastmobileapp/measuredefinitions/update/:id'
    redirectClose: pensoft/restcoastmobileapp/measuredefinitions
update:
    redirect: pensoft/restcoastmobileapp/measuredefinitions
    redirectClose: pensoft/restcoastmobileapp/measuredefinitions
preview: {  }
