title: Sites
modelClass: Pensoft\RestcoastMobileApp\Models\Site
list: $/pensoft/restcoastmobileapp/models/site/columns.yaml
recordUrl: 'pensoft/restcoastmobileapp/sites/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
