name: Site
modelClass: Pensoft\RestcoastMobileApp\Models\Site
form: $/pensoft/restcoastmobileapp/models/site/fields.yaml
defaultRedirect: pensoft/restcoastmobileapp/sites
create:
    redirect: 'pensoft/restcoastmobileapp/sites/update/:id'
    redirectClose: pensoft/restcoastmobileapp/sites
update:
    redirect: pensoft/restcoastmobileapp/sites
    redirectClose: pensoft/restcoastmobileapp/sites
preview: {  }
