title: Site Threat Impact Entry
modelClass: Pensoft\RestcoastMobileApp\Models\SiteThreatImpactEntry
list: $/pensoft/restcoastmobileapp/models/site-threat-impact-entry/columns.yaml
recordUrl: 'pensoft/restcoastmobileapp/sitethreatimpactentries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
