title: Threat Measure Impact Entry
modelClass: Pensoft\RestcoastMobileApp\Models\ThreatMeasureImpactEntry
list: $/pensoft/restcoastmobileapp/models/threat-measure-impact-entry/columns.yaml
recordUrl: 'pensoft/restcoastmobileapp/threatmeasureimpactentries/update/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
