<?php

namespace Pensoft\Restcoast\Models;

use Model;

class Site extends Model
{
    use \October\Rain\Database\Traits\Validation;

    public $table = 'pensoft_restcoast_sites';


    public $rules = [
        'name' => 'required',
    ];

    public $jsonable = ['content_blocks'];

    public $implement = [
        '@RainLab.Translate.Behaviors.TranslatableModel',
    ];

    public $translatable = [
        'name',
        'short_description',
        'content_blocks',
    ];

    public $belongsToMany = [
        'threats' => [
            Threat::class,
            'table' => 'pensoft_restcoast_site_threat',
            'order' => 'name'
        ]
    ];

    protected $fillable = [
        'name',
        'description',
        'content_blocks',
    ];


    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
